baseURL                = "https://naist9000-cyber.github.io/newpor2026/"
languageCode           = "ko-kr"
title                  = "정보톡톡"
defaultContentLanguage = "ko"
hasCJKLanguage         = true

[[module.imports]]
    path = "github.com/CaiJimmy/hugo-theme-stack/v3"

[pagination]
    pagerSize = 5

[permalinks]
    post = "/p/:slug/"
    page = "/:slug/"

[params]
    mainSections   = ["post"]
    rssFullContent = true
    favicon        = "img/avatar.png"
    
    [params.footer]
        since = 2026
        customText = "정보톡톡 - 세상의 정보를 한번 알아보자"

    [params.sidebar]
        emoji    = "✏️"
        subtitle = "세상의 정보를 한번 알아보자"
        avatar   = "img/avatar.png"

    [params.article]
        [params.article.license]
            enabled = false
        
    [params.comments]
        enabled = false

    [params.widgets]
        homepage = [
            { type = "search" },
            { type = "archives", params = { limit = 5 } },
            { type = "categories", params = { limit = 10 } },
            { type = "tag-cloud", params = { limit = 10 } },
        ]
        page     = [{ type = "toc" }]

[menu]
    [[menu.main]]
        identifier = "home"
        name       = "홈"
        url        = "/"
        weight     = 1
        [menu.main.params]
            icon = "home"

    [[menu.main]]
        identifier = "archives"
        name       = "아카이브"
        url        = "/archives/"
        weight     = 2
        [menu.main.params]
            icon = "archives"

    [[menu.main]]
        identifier = "search"
        name       = "검색"
        url        = "/search/"
        weight     = 3
        [menu.main.params]
            icon = "search"

    [[menu.social]]
        identifier = "github"
        name       = "GitHub"
        url        = "https://github.com/naist9000-cyber"
        [menu.social.params]
            icon = "brand-github"
