baseURL                = "https://demo.stack.cai.im/"
languageCode           = "ko-kr"
title                  = "정보톡톡"
# Theme i18n support
# See i18n folder for available languages
defaultContentLanguage = "ko"
# Set hasCJKLanguage to true if DefaultContentLanguage is a CJK language
# This will make .Summary and .WordCount behave correctly
hasCJKLanguage         = true

[[module.imports]]
    path = "github.com/CaiJimmy/hugo-theme-stack/v3"

[pagination]
    pagerSize = 5

[permalinks]
    post = "/p/:slug/"
    page = "/:slug/"

