[ko]
    languageName = "한국어"
    title        = "정보톡톡"
    weight       = 1

    [ko.params.sidebar]
        subtitle = "세상의 정보를 한번 알아보자"

[en]
    languageName = "English"
    title        = "Information TokTok"
    weight       = 2

    [en.params.sidebar]
        subtitle = "Let's explore information about the world"
