[ko]
    languageName = "한국어"
    title        = "정보톡톡"
    weight       = 1

    [ko.params.sidebar]
        subtitle = "세상의 정보를 한번 알아보자"

    [[ko.menu.main]]
        identifier = "home"
        name       = "홈"
        url        = "/"
        weight     = 1
        [ko.menu.main.params]
            icon = "home"

    [[ko.menu.main]]
        identifier = "archives"
        name       = "아카이브"
        url        = "/archives/"
        weight     = 2
        [ko.menu.main.params]
            icon = "archives"

    [[ko.menu.main]]
        identifier = "search"
        name       = "검색"
        url        = "/search/"
        weight     = 3
        [ko.menu.main.params]
            icon = "search"

    [[ko.menu.social]]
        identifier = "github"
        name       = "GitHub"
        url        = "https://github.com/naist9000-cyber"
        [ko.menu.social.params]
            icon = "brand-github"
