[[main]]
    identifier = "home"
    name       = "홈"
    url        = "/"
    weight     = 1
    [main.params]
        icon = "home"

[[main]]
    identifier = "archives"
    name       = "아카이브"
    url        = "/archives/"
    weight     = 2
    [main.params]
        icon = "archives"

[[main]]
    identifier = "search"
    name       = "검색"
    url        = "/search/"
    weight     = 3
    [main.params]
        icon = "search"

[[social]]
    identifier = "github"
    name       = "GitHub"
    url        = "https://github.com/naist9000-cyber"
    [social.params]
        icon = "brand-github"
