baseURL = "/"
languageCode = "en"
defaultContentLanguage = "en"
title = "My Hugo Blog - PaperMod"

enableRobotsTXT = true
enableEmoji = true

[params]
    env = "production"
    title = "My Hugo Blog"
    description = "A clean and minimal blog using PaperMod"
    keywords = ["Hugo", "PaperMod", "Blog"]
    author = "Heyjude"

    # PaperMod specific settings
    ShowReadingTime = true
    ShowShareButtons = true
    ShowPostNavLinks = true
    ShowBreadCrumbs = true
    ShowCodeCopyButtons = true

[menu]
    [[menu.main]]
        identifier = "archives"
        name = "Archives"
        url = "/archives"
        weight = 10
    [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags"
        weight = 20
    [[menu.main]]
        identifier = "categories"
        name = "Categories"
        url = "/categories"
        weight = 30

[markup]
    [markup.highlight]
        noClasses = false



theme = 'hugo-theme-stack'
